version: '3.9'
services:
    database:
        image: postgres
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DATABASE}
    # gateway:
    #     build: .
    #     ports:
    #         - "4000:4001"
    #     environment:
    #         - GATEWAY_PORT=${GATEWAY_PORT}